services:
  - type: web
    name: serverate
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        value: serveRate-super-secret-key-change-in-production-2026
      - key: MONGODB_URI
        value: "mongodb+srv://mugishaaimekevin_db_user:eeettt123456@cluster0.vmhyxl9.mongodb.net/?appName=Cluster0"
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        value: aimekevinmugisha@gmail.com
      - key: EMAIL_PASS
        value: kowf gcic ylwk ovyp
      - key: EMAIL_FROM
        value: aimekevinmugisha@gmail.com
      - key: RESEND_API_KEY
        value: your_resend_api_key_here
